export const FETCH_CHARACTER_BEGIN = "FETCH_CHARACTER_BEGIN";
export const FETCH_CHARACTER_SUCCESS = "FETCH_CHARACTER_SUCCESS";
export const FETCH_CHARACTER_FAILURE = "FETCH_CHARACTER_FAILURE";

export const FETCH_CHARACTER_HOMEWORLD_BEGIN =
  "FETCH_CHARACTER_HOMEWORLD_BEGIN";
export const FETCH_CHARACTER_HOMEWORLD_SUCCESS =
  "FETCH_CHARACTER_HOMEWORLD_SUCCESS";
export const FETCH_CHARACTER_HOMEWORLD_FAILURE =
  "FETCH_CHARACTER_HOMEWORLD_FAILURE";

export const FETCH_CHARACTER_FILMS_BEGIN = "FETCH_CHARACTER_FILMS_BEGIN";
export const FETCH_CHARACTER_FILMS_SUCCESS = "FETCH_CHARACTER_FILMS_SUCCESS";
export const FETCH_CHARACTER_FILMS_FAILURE = "FETCH_CHARACTER_FILMS_FAILURE";

export const FETCH_CHARACTER_SPECIES_BEGIN = "FETCH_CHARACTER_SPECIES_BEGIN";
export const FETCH_CHARACTER_SPECIES_SUCCESS =
  "FETCH_CHARACTER_SPECIES_SUCCESS";
export const FETCH_CHARACTER_SPECIES_FAILURE =
  "FETCH_CHARACTER_SPECIES_FAILURE";

export const FETCH_CHARACTER_VEHICLES_BEGIN = "FETCH_CHARACTER_VEHICLES_BEGIN";
export const FETCH_CHARACTER_VEHICLES_SUCCESS =
  "FETCH_CHARACTER_VEHICLES_SUCCESS";
export const FETCH_CHARACTER_VEHICLES_FAILURE =
  "FETCH_CHARACTER_VEHICLES_FAILURE";

export const FETCH_CHARACTER_STARSHIPS_BEGIN =
  "FETCH_CHARACTER_STARSHIPS_BEGIN";
export const FETCH_CHARACTER_STARSHIPS_SUCCESS =
  "FETCH_CHARACTER_STARSHIPS_SUCCESS";
export const FETCH_CHARACTER_STARSHIPS_FAILURE =
  "FETCH_CHARACTER_STARSHIPS_FAILURE";

export const FETCH_CHARACTERS_BEGIN = "FETCH_CHARACTERS_BEGIN";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_FAILURE = "FETCH_CHARACTERS_FAILURE";
